
management:
  endpoint:
    restart:
      enabled: true
    health:
      enabled: true
      probes:
        enabled: true
      show-details: always
    info:
      enabled: true

  endpoints:
    web:
      exposure:
        include: "*" # health,info,prometheus

  health:
    livenessState: # 开启 /actuator/health/liveness
      enabled: true
    readinessState: # 开启 /actuator/health/readiness
      enabled: true

  metrics:
    enable:
      jvm: true
    use-global-registry: false

    tags:
      region: us-east-1
      stack: prod

server:
  shutdown: graceful # 优雅停机


# spring 配置项目
# https://docs.spring.io/spring-boot/docs/current/reference/html/appendix-application-properties.html#common-application-properties



spring:
  profiles:
    active: dev
  # 输出带有颜色的控制台日志
  output:
    ansi:
      enabled: ALWAYS
  application:
    name: example-spring-multiple-svc-impl-transaction
  web: #spring.web.resources.add-mappings
    locale: zh_CN
    resources:
      add-mappings: false # 不要为我们工程中的资源文件建立映射
  mvc:
    throw-exception-if-no-handler-found: true
    # 暂时未发现该配置作用 ？todo @DateTimeFormat ？
    format:
      date: yyyy-MM-dd
      time: HH:mm:ss
      date-time: ${spring.mvc.format.date} ${spring.mvc.format.time}

  # todo 这个配置是干什么的
  main:
    allow-bean-definition-overriding: true
  #    lazy-initialization: true # 延迟初始化
  #    allow-circular-references: true # 允许循环引用
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

  jackson:
    time-zone: GMT+8 # 该设置与数据库 spring.jpa.properties.hibernate.jdbc.time_zone 保持一致
    date-format: yyyy-MM-dd HH:mm # 优先使用@JsonFormat设置的格式，否则使用该格式
    locale: zh_CN
    default-property-inclusion: non_null
    serialization:
      write-dates-as-timestamps: false # 将 date 数据转换为 timestamps(Long)，否则转换为 date-format 格式
      write_null_map_values: false # 不返还 null
  #    mapper:
  #      ACCEPT_CASE_INSENSITIVE_ENUMS: true

  #  datasource:
  #    data: database/data.sql # 单元测试提示错误
  #    schema:


  jpa:
    show-sql: true
    generate-ddl: false
    open-in-view: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        jdbc:
          time_zone: ${spring.jackson.time-zone} # 数据库时区与程序时区保持一致
        show_sql: true
        use_sql_comments: true
        format_sql: true
        enable_lazy_load_no_trans: true
  #        generate_statistics: true # metrics

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # serverTimezone=Asia/Shanghai 必须在URL追加时区设置
    url: jdbc:mysql://${DB_MYSQL_HOST}:3306/clever_framework_demo?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&serverTimezone=Asia/Shanghai
    username: ${DB_MYSQL_USER}
    password: ${DB_MYSQL_PASSWORD}

  data:
    rest:
      default-media-type: application/json
      return-body-on-create: true
      return-body-on-update: true
    web:
      pageable:
        one-indexed-parameters: true # 参数从1开始
  hateoas:
    use-hal-as-default-json-media-type: true





logging:
  level:
    root: DEBUG
    org.apache.coyote.http11: debug
    org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping: debug
    org.springframework.security: trace
    com.baomidou.dynamic.datasource: trace
